<?php

defined('BASEPATH') OR exit('No direct script access allowed');
/**
 * Pancake
 *
 * A simple, fast, self-hosted invoicing application
 *
 * @package     Pancake
 * @author      Pancake Dev TeamFF
 * @copyright   Copyright (c) 2010, Pancake Payments
 * @license     http://pancakeapp.com/license
 * @link        http://pancakeapp.com
 * @since       Version 1.0
 * @translated	Peter Ruiter - peterruiter.com
 */
// ------------------------------------------------------------------------

$lang = array(
    /** Global Words * */
    'global:overview' => 'Overzicht',
    'global:error' => 'Foutmelding',
    'global:pancakeby7am' => 'Pancake :1 by :2',
    'global:allrelatedmediacopyright' => 'Pancake en alle gerelateerde media is Copyright :1 :2',
    'global:insecure_action' => 'Onveilige actie werd geprobeerd, maar is onderschept',
    'global:disabled_in_demo' => 'Sommige onderdelen op deze pagina zijn uitgeschakeld voor de demo.',
    'global:estimates' => 'Offertes',
    'global:estimate' => 'Offerte',
    'global:incomplete_tasks' => 'Incomplete Taken',
    'global:completed_tasks' => 'Voltooide Taken',
    'global:projects' => 'Projecten',
    'global:project' => 'Project',
    'global:upload_failed' => 'Er is een fout opgetreden bij het uploaden van uw bestand. Probeer het opnieuw. Wanneer het probleem blijft bestaan, neem dan contact op met support@pancakeapp.com',
    'global:upload_not_allowed' => 'Het bestandstype van het bestand dat u probeert te uploaden is niet toegestaan. Als u een bestand moet uploaden van dat type, maar er dan eerst een .zip bestand van of een willekeurig ander archiefformaat.',
    'global:copied' => 'Gekopieerd!',
    'global:sentbutunpaid' => 'Openstaand (Verzonden maar niet betaald)',
    'global:task' => 'Taken',
    'global:clients' => 'Klanten',
    'global:users' => 'Gebruikers',
    'global:send_to_client' => 'Stuur naar klant',
    'global:couldnotsendemail' => 'Kon de email niet versturen. Controleer je instellingen.',
    'global:emailsent' => 'Email is verzonden!',
    'global:yes' => 'Ja',
    'global:no' => 'Nee',
    'global:notyetsent' => 'Nog niet verzonden naar klant',
    'global:dontshowagain' => "Dit niet nogmaals laten zien",
    'global:enable' => 'Aanzetten',
    'global:is_enabled' => 'Aangezet?',
    'global:is_completed' => 'Voltooid?',
    'global:Y' => 'J',
    'global:N' => 'N',
    'global:notes' => 'Notities',
    'global:description' => 'Beschrijving',
    'global:backtoadmin' => 'Terug naar Admin',
    'global:type' => 'Soort',
    'global:name' => 'Naam',
    'global:first_name' => 'Voornaam',
    'global:last_name' => 'Achternaam',
    'global:company' => 'Bedrijf',
    'global:for' => 'voor',
    'global:from' => 'van',
    'global:phone' => 'Telefoon',
    'global:email' => 'Email',
    'global:contacts' => 'Contacten',
    'global:week' => 'Wekelijks',
    'global:quarterly' => 'Kwartaallijks',
    'global:every_six_months' => 'Elke 6 maanden',
    'global:biyearly' => 'Elke 2 jaar',
    'global:month' => 'Maandelijks',
    'global:year' => 'Jaarlijks',
    'global:fax' => 'Fax',
    'global:mobile' => 'Mobiel',
    'global:address' => 'Adres',
    'global:api_key' => 'API Key',
    'global:website' => 'Website',
    'global:action' => 'Actie',
    'global:items' => 'Items',
    'global:reusableinvoiceitems' => 'Herbruikbare factuur items',
    'global:reusableinvoiceitems_description' => 'You should use Reusable Invoice Items when you want to reuse the same item in different invoices. To use them when you\'re creating or editing an invoice, simply start typing the name of the item you saved, and it\'ll offer to autocomplete the item\'s details for you.',
    'global:create_invoice_estimate' => 'Create invoices and estimates to collect money.',
    'global:createinvoice' => 'Factuur aanmaken',
    'global:paid' => 'Betaald',
    'global:unpaid' => 'Niet betaald',
    'global:overdue' => 'Achterstallig',
    'global:time_entries' => 'Tijdingaves',
    'global:invoices' => 'Facturen',
    'global:invoice' => 'Factuur',
    'global:estimate' => 'Offerte',
    'global:dashboard' => 'Dashboard',
    'global:settings' => 'Instellingen',
    'global:changepassword' => 'Wachtwoord veranderen',
    'global:logout' => 'Uitloggen',
    'global:status' => 'Status',
    'global:client' => 'Klant',
    'global:user' => 'Gebruiker',
    'global:title' => 'Titel',
    'global:subtitle' => 'Subtitel',
    'global:to' => 'Aan',
    'global:subject' => 'Onderwerp',
    'global:thanks' => 'Hartelijk bedankt!',
    'global:proposals' => 'Voorstellen',
    'global:proposal' => 'Voorstel',
    'global:reports' => 'Rapporten',
    'global:item' => 'Product/dienst',
    'global:report' => 'Rapport',
    'global:saveandinsert' => 'Opslaan en toevoegen',
    'global:details' => 'Details',
    'global:license_key' => 'Licentie code',
    'global:version' => 'Versie',
    'global:content' => 'Inhoud',
    'global:add' => 'Toevoegen',
    'global:edit' => 'Bewerken',
    'global:resend' => 'Opnieuw versturen',
    'global:sent' => 'Verzonden',
    'global:not_sent' => 'Niet verzonden',
    'global:view' => 'Bekijken',
    'global:delete' => 'Verwijderen',
    'global:remove' => 'Verplaatsen',
    'global:sort' => 'Sorteren',
    'global:deleteitem' => 'Product/dienst verwijderen',
    'global:dragtoreorder' => 'Sleep om opnieuw te ordenen',
    'global:start' => 'Start',
    'global:stop' => 'Stop',
    'global:start_timer' => 'Start Timer',
    'global:stop_timer' => 'Stop Timer',
    'global:created' => 'Aangemaakt',
    'global:updated' => 'Bijgewerkt',
    'global:update' => 'Bijwerken',
    'global:downloadpdf' => 'PDF Downloaden',
    'global:yesdelete' => 'Ja, verwijderen!',
    'global:confirm_emphisised' => 'je kunt dit niet meer ongedaan maken!',
    'global:color' => 'Kleur',
    'global:save' => 'Opslaan',
    'global:unknown' => 'Onbekend',
    'global:upload_ini_size' => 'Het bestand dat u probeert te uploaden overschrijdt de bestandsgrootte welke wordt opgelegd door uw PHP installatie.',
    'global:upload_error' => 'Er is een fout opgetreden bij het uploaden van het bestand. Probeer het opnieuw.',
    'global:recurring' => 'Periodiek',
    'global:unsent' => 'Niet verzonden',
    'global:converttoinvoice' => 'Wijzigen naar factuur',
    'global:viewpdf' => 'Toon PDF',
    'global:duplicate' => 'Kopieer',
    'global:urltosend' => 'Hier is de URL die u kunt verzenden:',
    'global:copytoclipboard' => 'Kopieer naar plakbord',
    'global:you_need_pancake_cron_job' => 'Om periodiek te factureren dient u de Pancake cronjob te gebruiken.',
    'global:if_you_dont_know_how_to_set_it_up' => 'Indien u niet weet hoe u dit gebruikt kijkt u, <a href="http://help.pancakeapp.com/customer/portal/articles/605703">hier</a>.',
    'global:optional_increment' => '<strong>Optioneel</strong> - wordt automatisch verhoogd',
    'login:ahoy' => 'Hoi!',
    'login:readytodothis' => 'Klaar om te starten?',
    'login:sup' => 'Hallo?',
    'global:actions' => 'Acties',
    /** Greetings * */
    'global:greetings' => array('Hoi!', 'Hallo,', 'He kanjer,', 'Vriend,'),
    /** End Greetings * */
    /** Dashboard * */
    'dashboard:collected' => 'Ontvangen',
    'dashboard:outstanding' => 'Uitstaan',
    'dashboard:latest_activity' => 'Recente activiteit',
    'dashboard:upcoming_tasks' => 'Aankomende taken',
    /** End Dashboard * */
    /** Users * */
// ==============================
// = LOGIN PAGE COMPLETED - Lee =
// ==============================
    'login:forgotinstructions' => 'Vul je email adres in zodat wij een email kunnen sturen om het wachtwoord te resetten.',
    'login:reset' => 'Reset &raquo;',
    'login:reset' => 'Wachtwoord resetten',
    'login:username' => 'Gebruikersnaam',
    'login:password' => 'Wachtwoord',
    'login:changepassword' => 'Wachtwoord aanpassen',
    'login:email' => 'Email adres',
    'login:login' => 'Inloggen',
    'login:logout' => 'Uitloggen',
    'login:remember' => 'Onthoud mij',
    'login:forgot' => 'Wachtwoord vergeten?',
    'login:cancel' => '&laquo; Annuleren',
    /** End Users * */
    /** Clients * */
    'clients:title' => 'Alle klanten',
    'clients:filter' => 'Klant filter',
    'clients:add' => 'Klant toevoegen',
    'clients:removefilter' => 'Remove Filter',
    'clients:edit' => 'Klant bewerken',
    'clients:noclienttitle' => 'Je moet eerst een paar klanten invoeren!',
    'clients:noclientbody' => 'zodat je facturen kunt sturen. Nu eentje toevoegen?',
    'clients:noclienttitlefilter' => 'No clients match your filter',
    'clients:hasnoinvoicetitle' => 'Top! Deze klant is ingesteld!',
    'clients:hasnoinvoicebody' => 'Laten we een factuur voor ze aanmaken en betaald krijgen! Nu eentje toevoegen?',
    'clients:added' => 'De klant is toegevoegd!',
    'clients:edited' => 'De klant is bijgewerkt!',
    'clients:deleted' => 'De klant is verwijderd!',
    'clients:does_not_exist' => 'Deze klant bestaat niet!',
    'clients:health_check' => 'Gezondheids controle',
    'clients:all' => 'Alle',
    'clients:delete_title' => 'Deze klant verwijderen?!?!',
    'clients:delete_message' => 'Weet je zeker dat je deze klant wilt verwijderen?<br />Zo ja, dan worden ook de facturen, projecten en alle offerte aanbiedingen van deze klant verwijderd.',
    'clients:clientaction' => '&nbsp;',
    'clients:passphrase' => 'Wachtwoord',
    'clients:bad_passphrase' => 'Wachtwoord is niet correct.',
    'clients:total_clients' => 'Total Clients',
    /** End Clients * */
    /** Contact Log * */
    'contact:title' => 'Recente contacthistorie',
    'contact:method' => 'Contactmethode',
    'contact:contact' => 'Contact',
    'contact:subject' => 'Onderwerp',
    'contact:content' => 'Inhoud',
    'contact:method' => 'Contactmethode',
    'contact:calling_title' => 'Bellen klant ":1"',
    // 'contact:view_all'		=>	'Toon alle',
    /** End Contact Log * */
    /** Invoices * */
    'invoices:markassent' => 'Markeer als verzonden',
    'invoices:invoicedate' => 'Factuurdatum',
    'invoices:sentbutunpaid' => 'Facturen verzonden naar de klant maar nog steeds niet betaald',
    'invoices:duplicated' => 'Factuur #:1 gekopieerd. Het nieuwe factuurnummer is #:2.',
    'invoices:all' => 'Alle facturen',
    'invoices:empty' => 'Nog geen facturen.',
    'invoices:overdue' => 'Achterstallige facturen',
    'invoices:paid' => 'Betaalde facturen',
    'invoices:recurringinvoices' => 'Periodieke facturen',
    'invoices:unsentinvoices' => 'Nog niet verzonden facturen',
    'invoices:unpaid' => 'Onbetaalde facturen',
    'invoices:thisinvoicewaspaidon' => 'Deze factuur is betaald op :1. Bedankt!',
    'invoices:senton' => 'Verzonden op :1',
    'invoices:paidon' => 'Betaald op :1',
    'invoices:paidonsingle' => 'Betaald op',
    'invoices:thisinvoiceisunpaid' => 'Deze factuur is nog niet betaald.',
    'invoices:noinvoicetitle' => 'Er zijn nog geen facturen!',
    'invoices:noinvoicebody' => 'Je kunt nu een factuur aanmaken voor een klant! <br /> Klanten zijn gek op facturen!',
    'invoices:send_now_title' => 'Nu factuur versturen?',
    'invoices:send_now_body' => 'Vul het formulier hieronder in en de factuur wordt door ons afgeleverd.',
    'invoices:newinvoice' => 'Factuur aanmaken',
    'invoices:send_now' => 'Factuur versturen',
    'invoices:timequantity' => 'Tijd/Aantal',
    'invoices:ratewithcurrency' => 'Tarief (:1)',
    'invoices:taxable' => 'Belastbaar',
    'invoices:total' => 'Totaal',
    'invoices:amount' => 'Bedrag',
    'invoices:due' => 'Te betalen voor',
    'invoices:subtotal' => 'Subtotaal',
    'invoices:totaltax' => 'Totaal BTW',
    'invoices:filestodownload' => 'Bestanden voor Download',
    'invoices:added' => 'De factuur is toegevoegd!',
    'invoices:fileswillbeavailableafterpay' => 'Deze bestanden zijn beschikbaar om te downloaden zodra de factuur volledig is betaald.',
    'invoices:no_payment_gateways_enabled' => 'Er zijn geen betaal providers aangezet, dit maakt het natuurlijk lastig om betaald te krijgen. Aanzetten in <a href=":1">Instellingen</a>',
    'invoices:invoicenumber' => 'Factuur #:1',
    'invoices:number' => 'Factuur #',
    'invoices:type' => 'Soort factuur',
    'invoices:is_recurring' => 'Periodiek / herhaling?',
    'invoices:is_paid' => 'Betaald?',
    'invoices:is_sent' => 'Verzonden?',
    'invoices:date_entered' => 'Datum aangemaakt',
    'invoices:delete_title' => 'Deze factuur verwijderen?',
    'invoices:delete_message' => 'Weet je zeker dat je deze factuur wilt verwijderen?',
    'invoices:create' => 'Factuur aanmaken',
    'invoices:edit' => 'Factuur bewerken',
    'invoices:amountrequired' => 'Het bedrag is verplicht',
    'invoices:currencydoesnotexist' => 'Deze valuta bestaat niet.',
    'invoices:unique_id' => 'Uniek ID',
    'invoices:willreoccurin' => 'Deze factuur wordt herhaald op :1.',
    'invoices:willbesentautomatically' => 'De klant wordt per email op de hoogte gebracht over deze factuur op :1.',
    'invoices:thisisareoccurrence' => 'Deze factuur is een herhaling van factuur :1.',
    'invoices:clientlastnotifiedon' => 'De klant is per email geinformeerd over deze factuur op :1.',
    'invoices:simple' => 'Eenvoudig',
    'invoices:simple_help' => 'Een eenvoudige factuur heeft geen extra regels voor producten/diensten. Alleen een totaalbedrag.',
    'invoices:detailed' => 'Gedetailleerd',
    'invoices:detailed_help' => 'Gedetailleerde facturen kunnen meerdere regels voor producten/diensten bevatten.',
    'invoices:estimate_help' => 'Offertes zijn gedetailleerde voorstellen die niet factureerbaar zijn.',
    'invoices:unpaid_totalamount' => 'Onbetaald / Totaal bedrag',
    'invoices:saveinvoice' => 'Factuur opslaan',
    'invoices:deleted' => 'De factuur is verwijderd!',
    'invoices:view' => 'Bekijk factuur',
    'invoices:is_viewable' => 'Toon in klantgedeelte?',
    'invoices:no_invoices' => 'Er zijn geen facturen.',
    'invoices:addedsuccess' => 'U heeft een factuur toegevoegd voor',
    'invoices:invoice' => 'factuur',
    'invoices:addedconf' => 'U heeft factuur # <strong>:1</strong> toegevoegd, totaal <strong>:2</strong> voor :3:4.',
    'invoices:preview' => 'Voorvertoning factuur',
    'invoices:editinvoice' => 'Bewerk factuur #:1',
    'invoices:messageupdated' => 'De factuur is bijgewerkt!',
    'invoices:resend' => 'Factuur opnieuw verzenden',
    'invoices:client_viewed' => ':1 bekeek factuur #:2 op :3',
    'invoices:client_paid' => ':1 betaalde factuur #:2 op :3',
    /** End Invoices * */
    /** Estimates * */
    'estimates:attachedtoproposal' => 'Bijgevoegd bij voorstel #:1',
    'estimates:duplicated' => 'Offerte #:1 gekopieerd. Het nieuwe offertenummer is #:2.',
    'estimates:alltitle' => 'Alle offertes',
    'estimates:attachingtoproposal' => 'Offerte op voorstel wordt nu bijgevoegd, moment aub...',
    'estimates:delete_title' => 'Deze offerte verwijderen?',
    'estimates:delete_message' => 'Weet je zeker dat je deze offerte wilt verwijderen?',
    'estimates:createnew' => 'Nieuwe offerte aanmaken',
    'estimates:generate_estimate' => 'Genereer Offerte',
    'estimates:converted' => 'Offerte #:1 gewijzigd naar een factuur.',
    'estimates:noestimatetitle' => 'Er zijn geen offertes',
    'estimates:noestimatesforthisclient' => 'Er zijn geen offertes voor deze klant.',
    'estimates:deleted' => 'De offerte is verwijderd!',
    'estimates:noestimatebody' => 'Dit zou je eigenlijk nog moeten doen! Wilt je er eentje aanmaken?',
    'estimates:estimatenumber' => 'Offerte #:1',
    'estimates:view' => 'Toon offerte',
    'estimates:no_estimates' => 'Er zijn geen offertes.',
    'estimates:addedsuccess' => 'U heeft een offerte toegevoegd voor',
    'estimates:estimate' => 'offerte',
    'estimates:added' => 'Succes! De offerte is toegevoegd.',
    'estimates:addedconf' => 'U heeft offerte # <strong>:1</strong> toegevoegd, totaal <strong>:2</strong> voor :3:4.',
    'estimates:send_now_title' => 'Offerte nu verzenden?',
    'estimates:send_now_body' => 'Vul het onderstaande formulier in en we verzenden deze offerte direct voor u.',
    'estimates:send_now' => 'Verzend offerte',
    'estimates:edit' => 'Bewerk offerte',
    'estimates:preview' => 'Voortvertoning offerte',
    'estimates:editestimate' => 'Bewerk offerte #:1',
    'estimates:messageupdated' => 'De offerte is bijgewerkt!',
    'estimates:resend' => 'Offerte opnieuw versturen',
    /** End Estimates * */
    /** Projects * */
    'projects:status_id' => 'Taak Status',
    'projects:projected' => 'Ingeschat',
    'projects:projected_hours' => 'Ingeschatte uren',
    'projects:navigationitem' => 'Projecten',
    'projects:hours_worked' => 'Aantal gewerkte uren',
    'projects:hours_worked_short' => 'Uren gewerkt',
    'projects:alltitle' => 'Alle projecten',
    'projects:totalprojects' => 'Totaal aantal Projecten',
    'projects:noprojecttitle' => 'Er zijn nog geen projecten!',
    'projects:noprojecttext' => 'Wilt je er eentje aanmaken? ',
    'projects:add' => 'Nieuw project',
    'projects:doesnotexist' => 'Het project dat u probeert te bekijken bestaat niet.',
    'projects:edit' => 'Bewerk project',
    'projects:delete' => 'Verwijder project',
    'projects:project' => 'Project',
    'projects:due_date' => 'Vervaldag',
    'projects:is_completed' => 'Voltooid?',
    'projects:manage_project' => 'Beheer Project',
    'projects:areyousuredeletetask' => 'Weet je zeker dat je deze taak wilt verwijderen?',
    'projects:add_time' => 'Tijd toevoegen',
    'projects:add_hours' => 'Uren toevoegen',
    'projects:generate_invoice' => 'Factuur genereren',
    'projects:no_projects' => 'Er zijn geen projecten.',
    'projects:archive_proj' => 'Project archiveren',
    'projects:unarchive_proj' => 'Project de-archiveren',
    'projects:archive' => 'Bekijk archief',
    'projects:active' => 'Actieve Projecten',
    'projects:archived' => 'Gearchiveerde Projecten',
    'projects:noarchivedprojecttitle' => 'U heeft geen gearchiveerde projects.',
    'projects:noarchivedprojecttext' => 'U kunt een project archiveren vanuit uw projectpagina ',
    'projects:allarchivedtitle' => 'Alle gearchiveerde projecten',
    'projects:templatize' => 'Opslaan als template',
    /** End Projects * */
    /** Milestones * */
    'milestones:add' => 'Toevoegen Milestone',
    'milestones:edit' => 'Bewerken Milestone',
    'milestones:delete' => 'Verwijderen Milestone',
    'milestones:milestone' => 'Milestone',
    'milestones:target_date' => 'Geplande afrondingsdatum',
    'milestones:assigned_user' => 'Toegewezen gebruiker',
    'milestones:select_default' => '-- Geen Milestone --',
    'milestones:no_milestone' => 'Taken zonder Milestone',
    'milestones:add_success' => 'Milestone ":1" succesvol toegevoegd!',
    'milestones:edit_success' => 'Milestone ":1" edited successfully!',
    'milestones:add_failed' => 'Milestone ":1" kon niet worden toegevoegd.',
    'milestones:edit_failed' => 'Milestone ":1" could not be added.',
    'milestones:are_you_sure_delete' => 'Weet u zeker dat u deze Milestone wilt verwijderen?',
    'milestones:delete_success' => 'Milestone ":1" succesvol verwijderd!',
    'milestones:does_not_exist' => 'Deze Milestone bestaat niet.',
    'milestones:target_date' => 'Geplande afrondingsdatum',
    'milestones:select_assignee_default' => 'No Assignee',
    /** End Milestones * */
    /** Proposals * */
    'proposal:outline' => 'Voorstel schema',
    /** End Proposals * */
    /** Reports * */
    'reports:perclient' => 'per klant',
    'reports:datefrom' => 'Van',
    'reports:allclients' => 'Alle klanten',
    'reports:dateto' => 'Aan',
    'reports:byclient' => 'Klant',
    'reports:view' => 'Rapport bekijken',
    'reports:show_all' => 'Toon rapporten',
    'reports:nodata' => 'Nr :1.',
    /** End Reports * */
    /** Currencies * */
    'currencies:default' => '[Standaard] :1',
    'currencies:cad' => 'Canadian Dollar',
    'currencies:eur' => 'Euro',
    'currencies:usd' => 'U.S. Dollar',
    'currencies:gbp' => 'Pound Sterling',
    'currencies:hkd' => 'Hong Kong Dollar',
    'currencies:php' => 'Philippine Peso',
    'currencies:zar' => 'South Africa, Rand',
    /** End Currencies * */
    /** Proposals * */
    'proposals:duplicated' => 'Voorstel #:1 gekopieerd. Het nieuwe voorstelnummer is #:2.',
    'proposals:usesectiontemplate' => 'Gebruik deze Sectie Template',
    'proposals:showcontents' => 'Toon inhoud',
    'proposals:hidecontents' => 'Verberg inhoud',
    'proposals:deletepremadesection' => 'Verwijder Sectie Template',
    'proposals:nopremadesections' => 'U heeft geen opgeslagen Sectie Templates.',
    'proposals:newproposal' => 'Nieuw voorstel',
    'proposals:estimatexfory' => 'Offerte #:1 - :2',
    'proposals:number' => 'Voorstel #',
    'proposals:all' => 'Alle voorstellen',
    'proposals:noproposaltitle' => "Er zijn geen voorstellen!",
    'proposals:noproposalbody' => "Je zou nu een voorstel moeten aanmaken. Echt waar.",
    'proposals:rejected' => 'Afgewezen op :1',
    'proposals:accepted' => 'Geaccepteerd op :1',
    'proposals:lastviewed' => 'Recent bekeken door klant op :1, at :2',
    'proposals:neverviewed' => 'niet bekeken door klant',
    'proposals:noanswer' => 'Geen antwoord',
    'proposals:createproposal' => 'Voorstel aanmaken',
    'proposals:editproposal' => 'Voorstel bewerken',
    'proposals:createdsuccessfully' => 'Voorstel gemaakt!',
    'proposals:sections' => 'Secties',
    'proposals:section' => 'Sectie',
    'proposals:createsection' => 'Nieuwe sectie toevoegen',
    'proposals:createpage' => 'Pagina toevoegen',
    'proposals:emptysection' => '(geen titel)',
    'proposals:emptycontents' => '(geen inhoud)',
    'proposals:emptysubtitle' => '(geen subtitel)',
    'proposals:for' => 'Voorstel voor:',
    'proposals:pagexofcount' => 'Pagina :1 van :2',
    'proposals:saving' => 'Bezig met opslaan...',
    'proposals:save' => 'Voorstel opslaan',
    'proposals:savepremade' => 'Opslaan als sectie template',
    'proposals:addestimate' => 'Offerte toevoegen',
    'proposals:saved' => 'Opgeslagen!',
    'proposals:createandedit' => 'Volgende: Voorstel inhoud bewerken',
    'proposals:delete_message' => 'Weet je zeker dat je dit voorstel wil verwijderen?',
    'proposals:createpremadesection' => 'Toevoegen van sectie template',
    'proposals:selected_attachments' => 'Selecteer offerte',
    'proposals:attach_selected_estimate' => 'Geselecteerde offerte bijvoegen',
    'proposals:proposal' => 'Voorstel',
    'proposals:status' => 'Status',
    'proposals:view' => 'Toon voorstel',
    'proposals:estimate' => 'Offete',
    'proposals:na' => 'N/A',
    'proposals:no_proposals' => 'Er zijn geen voorstellen.',
    'proposals:kitchennotice' => 'Let op: Voorstellen zullen worden getoond in de :1 wanneer de klant de voorstellink heeft bekeken. Dit betekend dat u zoveel wijzigingen kunt doen als u wilt zonder dat de klant het ziet totdat u dat wilt.',
    /** End Proposals * */
    /** Tasks * */
    'tasks:task' => 'Taak',
    'tasks:edit_succeeded' => 'Taak succesvol gewijzigd.',
    'tasks:hours' => 'Uren',
    'tasks:due_date' => 'Vervaldatum',
    'tasks:is_completed' => 'Voltooid?',
    'tasks:timer' => 'Tijdklok',
    'tasks:rate' => 'Tarief',
    'tasks:default_rate' => 'Standaard tarief',
    'tasks:entries' => 'Tijd regels',
    'tasks:view_entries' => 'Bekijk reacties',
    'tasks:edit_entry' => 'Wijzig tijd-regel',
    'tasks:create' => "Taak aanmaken",
    'tasks:create_sub' => "Toevoegen Sub-Taak",
    'tasks:task_parent' => "Task Parent",
    'tasks:edit' => "Wijzig taak",
    'tasks:create_succeeded' => "De taak is aangemaakt!",
    'tasks:no_task_title' => 'Hmm, nog geen taken...',
    'tasks:no_task_message' => 'Je zou er een paar kunnen maken!',
    'tasks:is_viewable' => 'Tonen in klantgedeelte?',
    'tasks:no_milestones' => 'Taken zonder milestones',
    'tasks:not_related_to_a_task' => "-- Niet gerelareerd aan een taak --",
    'tasks:select_parent_default' => '-- Geen bovenliggende taak --',
    'tasks:timers_running' => 'Timer loopt',
    'tasks:task_completed_by' => ':1 voltooide taak :2 om :3',
    'tasks:discussion' => 'Discussie: ',
    /** Users * */
    'users:create_user' => 'Nieuwe gebruiker',
    /** Items * */
    'items:name' => 'Product/dienst naam',
    'items:description' => 'Product/dienst beschrijving',
    'items:qty_hrs' => 'Aantal / Uren',
    'items:quantity' => 'Aantal',
    'items:rate' => 'Tarief',
    'items:tax_rate' => 'BTW tarief',
    'items:cost' => 'Prijs',
    'items:line_items' => 'Regel producten/diensten',
    'items:add' => 'Product/dienst toevoegen',
    'items:edit' => 'Product/dienst bewerken',
    'items:noitemtitle' => 'Er zijn nog geen producten/diensten!',
    'items:noitembody' => 'Je zou nu een paar producten/diensten kunnen toevoegen, het zorgt ervoor dat het aanmaken van facturen een stuk makkelijker gaat!',
    'items:delete_title' => 'Dit product/dienst verwijderen?',
    'items:delete_message' => 'Weet je zeker dat je product/dienst ":1" wilt verwijderen?',
    'items:type' => 'Type',
    'items:select_standard' => 'Standaard',
    'items:select_expense' => 'Uitgave',
    'items:add_expense_to_project' => 'Toevoegen Uitgave',
    /** Transactions * */
    'transactions:paymentcancelled' => 'Betaling geannuleerd',
    'transactions:extrapaymentcancelled' => 'Uw betaling is geannuleerd.',
    'transactions:paymentreceived' => 'Betaling ontvangen!',
    'transactions:fee_applied' => 'Gezien :1 een transactie fee oplegt, hebben we een :2% opslag toegevoegd.',
    'transactions:orderbeingprocessed' => 'Moment aub, uw opdracht wordt verwerkt en u wordt doorgestuurd naar de :1 website.',
    'transactions:ifyouarenotredirected' => 'Als u niet automatisch binnen 5 seconden wordt doorgestuurd naar :1 ...',
    'transactions:thankyouforyourpayment' => 'Hartelijk dank voor uw betaling. U ontvangt zo spoedig mogelijk een ontvangst bevestiging per email.',
    'transactions:ifyouhavefilesyouwillgetanemail' => 'Als er bestanden zijn die nog aan u afgeleverd moeten worden, ontvangt u een email met de download link.',
    'transactions:ifyoudonotreceiveemail' => 'Als u binnen een uur geen email hebt ontvangen neem dan contact op met :1',
    /** End Transactions * */
    /** Timesheets * */
    'timesheet:taskname' => 'Taak naam',
    'timesheet:starttime' => 'Begintijd',
    'timesheet:endtime' => 'Eindtijd',
    'timesheet:timeframe' => 'Tijdschema',
    'timesheet:duration' => 'Duur',
    'timesheet:date' => 'Datum',
    'timesheet:forproject' => 'Tijdrooster voor project ":1"',
    'timesheet:timesheet' => 'Tijdrooster',
    'timesheet:for' => 'Tijdrooster voor:',
    'timesheet:totalbillable' => 'Totaal te factureren uren',
    'timesheet:view_pdf' => 'Bekijk tijdrooster (PDF)',
    /** End Timesheets * */
    /** Frontend * */
    'frontend:hithere' => 'Hallo!',
    'frontend:followthemaillinkdude' => 'Om te zorgen dat u de facturen kunt bekijken moet u op de volledige link klikken die gestuurd is per email. Bijv. :1.',
    'frontend:contactadminforassistance' => 'Probeer dit eerst of neem contact op :1 @ :2 voor assistentie',
    /** End Frontend * */
    /** Settings * */
    'settings:task_statuses' => "Taak Statussen",
    'settings:background_color' => "Achtergrondkleur",
    'settings:text_color' => "Tekstkleur",
    'settings:text_shadow' => "Tekstschaduw",
    'settings:box_shadow' => "Boxschaduw",
    'settings:allowed_extensions' => 'Toegestande upload extensies',
    'settings:comma_separated' => 'komma-gescheiden',
    'settings:pdf_page_size' => 'PDF Pagina grootte',
    'settings:default_invoice_notes' => 'Standaard factuur notities',
    'settings:default_invoice_title' => 'Standaard factuurtitel',
    'settings:default_invoice_due_date' => 'Standaard vervaldatum',
    'settings:autosave_proposals' => 'Autosave Voorstellen',
    'settings:default_invoice_due_date_explain' => 'dagen nadat de factuur is aangemaakt. Als u geen standaard datum wilt laat u dit veld leeg.',
    'settings:testemailsettings' => 'Test Email instellingen',
    'settings:kitchen_route' => 'Klant toegang link voorvoegsel',
    'settings:kitchen_route_explain' => "(bijv. :1)",
    'settings:include_remittance_slip' => 'Overschrijvingsstrook',
    'settings:include_remittance_slip_explain' => "Wanneer aangevinkt zullen de PDF facturen een overschrijvingsstrook bevatten.",
    'settings:items_per_page' => 'Items per pagina',
    'settings:items_per_page_explain' => 'Aantal items (facturen/voorstellen/offertes/projecten/taken) om per pagina te tonen.',
    'settings:send_x_days_before' => 'Standaard "verzend dagen van te voren"',
    'settings:send_x_days_before_explain' => "Standaard aantal dagen voordat een periodieke factuur vervalt verzenden naar de klant.",
    'settings:file_to_import' => 'Bestand om te importeren',
    'settings:export_types' => 'Pancake exporteert alles in JSON formaat.',
    'settings:file_should_be_csv' => 'Alleen CSV en XML bestanden worden ondersteund.',
    'settings:importnow' => 'Importeer nu!',
    'settings:whatimporting' => 'Wat bent u aan het importeren?',
    'settings:whatexporting' => 'Wat bent u aan het exporteren?',
    'settings:nouploadedimportfile' => 'U heeft geen bestand geupload om te importeren.',
    'settings:import' => 'Importeren',
    'settings:importedclients' => ':1 klanten succesvol geïmporteerd.',
    'settings:importedinvoices' => ':1 facturen succesvol geïmporteerd.',
    'settings:importedestimates' => ':1 offertes succesvol geïmporteerd.',
    'settings:importedtime_entries' => ':1 tijd regels succesvol geïmporteerd.',
    'settings:xwereduplicates' => ':1 waren duplicaten en zijn genegeerd.',
    'settings:import_desc' => 'Importeer data naar Pancake.',
    'settings:export' => 'Exporteren',
    'settings:exportnow' => 'Exporteer nu!',
    'settings:importexport' => 'Importeren / Exporteren',
    'settings:removelogo' => 'Verwijder Logo',
    'settings:wrong_license_key' => 'De licentie code die is ingevuld is ongeldig.',
    'settings:noopenssl' => 'Je PHP server heeft geen OpenSSL geconfigureerd, wat betekend dat je geen gebruik kunt maken van Gmail of Google Apps om email te versturen. Neem cotact op met je hosting provider om te zeggen dat je OpenSSL nodig hebt.',
    'settings:logoremoved' => 'Logo verwijderen is gelukt!',
    'settings:save' => 'Instellingen opslaan',
    'settings:logodimensions' => 'Het logo moet 240 x 106 pixels zijn (breedte x hoogte).',
    'settings:logoformatsallowed' => 'BMP, PNG, JPG (JPEG) en GIF is toegestaan.',
    'settings:ftp_user' => 'FTP Gebruiker',
    'settings:ftp_pass' => 'FTP Wachtwoord',
    'settings:ftp_path' => 'FTP Pad',
    'settings:ftp_port' => 'FTP Poort',
    'settings:ftp_pasv' => 'Passieve modus?',
    'settings:nophpupdates' => "Vanwege de server configuratie is het nodig om je FTP gegevens in te vullen zodat Pancake automatisch kan worden bijgewerkt. Deze gegevens worden intern gebruikt door Pancake en nooit aan derden verstrekt.",
    'settings:ftp_host' => 'FTP Host',
    'settings:uptodate' => 'Pancake is bijgewerkt (:1)',
    'settings:newversionavailable' => 'Er is een nieuwe versie van Pancake beschikbaar (:1)!',
    'settings:updatenow' => 'Nu bijwerken!',
    'settings:youneedtoconfigurefirst' => 'Je Pancake is nog niet geconfigureerd om automatisch te worden bijgewerkt. Vul je FTP gegevens hieronder in en klik op "Instellingen opslaan".<br /> Pancake zal dan worden bijgewerkt.',
    'settings:general' => 'Algemeen',
    'settings:email_templates' => 'Email templates',
    'settings:taxes' => 'Belastingen',
    'settings:currencies' => 'Valuta',
    'settings:branding' => 'Huisstijl',
    'settings:payment_methods' => 'Betaal methodes',
    'settings:feeds' => 'Feeds',
    'settings:api_keys' => 'API Keys',
    'settings:site_name' => 'Site naam',
    'settings:language' => 'Taal',
    'settings:timezone' => 'Tijdzone',
    'settings:notify_email' => 'Kennisgeving email',
    'settings:currency' => 'Valuta',
    'settings:theme' => 'Frontend thema',
    'settings:admin_theme' => 'Admin thema',
    'settings:admin_name' => 'Admin naam',
    'settings:date_format' => 'Datum notatie',
    'settings:task_time_interval' => 'Taak tijd Interval',
    'settings:mailing_address' => 'Mailing adres',
    'settings:default_subject' => 'Standaard onderwerp',
    'settings:default_contents' => 'Standaard bericht',
    'settings:new_estimate' => 'Nieuwe offerte',
    'settings:new_invoice' => 'Nieuwe factuur',
    'settings:new_proposal' => 'Nieuw voorstel',
    'settings:paid_notification' => 'Kennisgeving betaling',
    'settings:payment_receipt' => 'Ontvangen betaling',
    'settings:logo' => 'Je logo',
    'settings:frontend_css' => 'Frontend eigen CSS',
    'settings:backend_css' => 'Backend eigen CSS',
    'settings:rss_password' => 'RSS wachtwoord',
    'settings:default_feeds' => 'Standaard feeds',
    'settings:cron_job_feed' => 'Cron Job',
    'settings:feed_generator' => 'Feed Generator',
    'settings:your_link' => 'Je Link',
    'settings:bcc' => 'BCC',
    'settings:automaticallybccclientemail' => 'Een kopie van alle emails van klanten worden automatisch gestuurd naar het kennisgevings email adres (zoals hierboven is aangegeven)',
    'settings:api_note' => 'Naam / Notitie',
    'settings:api_key' => 'Key',
    'settings:tax_name' => 'BTW naam',
    'settings:tax_value' => 'Waarde',
    'settings:tax_reg' => 'Registratie / Code',
    'settings:add_tax' => 'Andere belasting toevoegen',
    'settings:currency_name' => 'Valuta naam',
    'settings:currency_code' => 'Valuta code',
    'settings:exchange_rate' => 'Wisselkoers',
    'settings:add_currency' => 'Andere valuta toevoegen',
    /** End Settings * */
    'update:ifyourenotsurecontactus' => "Als je niet zeker weet wat je moet doen <a href='http://pancakeapp.com/forums/newtopic/2/'>start dan een nieuw support onderwerp in het forum</a>.",
    'update:youmodified' => 'Je wijzigde',
    'update:youdeleted' => 'Je verwijderde',
    'update:loadingpleasewait' => 'Laden, een moment geduld...',
    'update:errordownloading' => 'Er is een systeemupdate voor Pancake bestchikbaar, maar er zijn momenteel problemen met het binnenhalen van deze update.',
    'update:herearestepstofix' => 'Hier zijn enkele stappen die u kunt proberen om het probleem op te lossen:',
    'update:makesureuploadsiswritable' => 'Wees er zeker van dat de uploads map schrijfbaar is (CHMOD 0777).',
    'update:deletepancakesystemupdate' => 'Verwijder de pancake-update-system map (binnen de uploads map), en alle inhoud van deze map.',
    'update:loadpancakeagain' => "Herlaad Pancake. Als de fout blijft bestaan neem dan contact op met support@pancakeapp.com en we zullen u proberen te assisteren.",
    'update:whatschanged' => "Wat is nieuw in :1",
    'update:ftp_conn' => 'Pancake kon geen verbinding maken met de FTP host.',
    'update:ftp_login' => 'Pancake kon niet inloggen via FTP (verkeerde FTP gebruikersnaam/wachtwoord?).',
    'update:ftp_chdir' => 'Pancake kon het FTP pad niet instellen (pad bestaat waarschijnlijk niet).',
    'update:ftp_no_uploads' => 'Pancake Kreeg geen toegang om bestanden te uploaden via FTP.',
    'update:ftp_indexwrong' => 'Het FTP pad wat is opgegeven is onjuist. Het moet een pad zijn naar Pancake\'s directory.',
    'update:ftp_indexnotfound' => 'Het FTP pad wat is opgegeven is onjuist. Het moet een pad zijn naar Pancake\'s directory.',
    'update:update_conflict' => 'Je moet een aantal bestanden bijwerken sinds de laatste update. Om te zorgen dat je aangepaste bestanden veilig zijn is hier een lijst met bestanden die je hebt aangepast en waarschijnlijk conflicteren met de laatste update.',
    'update:update_no_perms' => 'Pancake heeft onvoldoende rechten om zichzelf te updaten, en heeft geen toegang tot een FTP account om zichzelf te updaten. Update kan niet doorgaan.',
    'update:review_files' => 'Lees deze bestanden en maak een backup voordat je verder gaat. Als de upgrade voltooid is kunt je je wijzigingen terugzetten. Vervang niet zomaar de bijgewerkte bestanden door je verouderde kopies, omdat Pancake dan niet meer goed werkt.',
    'update:internetissues' => "Pancake kan geen verbinding maken met internet.",
    'update:pancakeneedsinternet' => 'Om Pancake goed te laten functioneren, moet je server het toestaan om informatie van het internet te halen.',
    'update:maybefirewall' => "Het lijkt erop dat je server Pancake geen toegang tot internet geeft. Dit kan komen door een firewall probleem op je server. Neem hiervoor contact op met je hosting provider. Vraag om PHP toegang tot manage.pancakeapp.com.",
    'update:nointernetaccess' => 'Geen internet toegang',
    'update:pancakeupdated' => 'Pancake is bijgewerkt van :1 naar :2',
    /** Action Logger  * */
    /** End Action Logger * */
    /** Partial Payments * */
    'partial:partialpayments' => 'Betalingsplan',
    'partial:totalamounttobepaid' => "Totaalbedrag te betalen door klant",
    'partial:amountlefttobeadded' => "Bedrag over om toe te voegen aan betalingsplan",
    'partial:amounttoobig' => "Bedrag dat moet worden verwijderd uit betalingsplan",
    'partial:noamountneeded' => "Uw betalingsplan is compleet.",
    'partial:amount' => 'Bedrag',
    'partial:add_payment' => 'Toevoegen betaling',
    'partial:dueon' => 'Verschuldigd op',
    'partial:addanother' => 'Voeg een ander deel aan deze betaling toe',
    'partial:disabledforrecurring' => 'Herhaling facturen zijn beperkt tot een deel van de betalingen',
    'partial:paymentdetails' => 'Betalingsgegevens',
    'partial:wrongtotal' => 'De som van alle onderdelen van je betalingsplan komt niet overeen met het totaal bedrag van de facturatie.',
    'partial:problemsaving' => 'Er is een fout opgetreden tijdens het opslaan van het betalingsplan. Probeer het nogmaals.',
    'partial:wrongtotalbutsaved' => 'De som van alle onderdelen van je betalingsplan komt niet overeen met het totaal bedrag van de facturatie.<br />De aanpassingen voor je factuur zijn opgeslagen, maar je moet de fout in het betalingsplan wel herstellen.',
    'partial:problemsavingbutsaved' => 'Er is een fout opgetreden tijdens het opslaan van het betalingsplan. Probeer het nogmaals.<br />De aanpassingen voor je factuur zijn opgeslagen, alleen het betalingsplan niet.',
    'partial:savepaymentdetails' => 'Betalingsgegevens opslaan',
    'partial:partpaidthanks' => "Dit deel van de factuur is betaald. Hartelijk dank.",
    'partial:proceedtopayment' => 'Overgaan tot betaling',
    'partial:topaynowgoto' => 'Om direct te betalen ga naar :1',
    'partial:dueondate' => 'Verschuldigd op :1',
    'partial:paymentmethod' => 'Betalingsmethode',
    'partial:paymentdate' => 'Datum betaling',
    'partial:paymentstatus' => 'Status betaling',
    'partial:transactionid' => 'Transactie ID',
    'partial:markaspaid' => 'Markeren als betaald',
    'partial:transactionfee' => 'Transactiekosten',
    /** End Partial Payments * */
    /** Payment Gateways * */
    'paypal:clickhere' => 'Klik hier',
    'authorize:transaction_key' => 'Transactie Key',
    'paypal:email' => 'PayPal Email',
    'paypal:fee' => 'PayPal Fee (%)',
    'paypalpro:paypalpro' => 'PayPal Payments Pro',
    'paypalpro:viacreditcard' => 'Pay via Credit Card',
    'cash:cash' => 'Contant',
    'check:check' => 'Cheque',
    'moneyorder:moneyorder' => 'Money Order',
    'creditcard:creditcard' => 'CreditCard',
    'banktransfer:banktransfer' => 'Overschrijving',
    'gateways:errorupdating' => 'Er is een fout opgetreden tijdens het bijwerken van de instellingen van je betalingsmethode. Neem contact op met support.',
    'gateways:paymentmethods' => 'Betalingsmethodes',
    'gateways:selectpaymentmethod' => 'Selecteer betalingsmethode',
    'gateways:nogatewayused' => 'Geen methode gebruikt: Deel is niet betaald',
    'gateways:completed' => 'Voltooid',
    'gateways:refunded' => 'Terugbetaald',
    'gateways:unpaid' => 'Onbetaald',
    'gateways:paymentrejected' => ':1 betaling afgewezen',
    'gateways:rejectedemail' => 'Pancake kreeg bericht van een :1 betaling welke een van uw klanten (:2) maakte, maar :1 heeft deze afgewezen.',
    'gateways:pending' => 'In behandeling',
    'gateways:returntowebsite' => 'Ga terug naar :1',
    'gateways:cc_type' => 'CreditCard type',
    'gateways:cc_number' => 'CreditCard nummer',
    'gateways:cc_exp' => 'Vervaldatum',
    'gateways:cc_code' => 'CVV Code',
    'gateways:payment_details' => 'Betalingsdetails',
    'gateways:api_signature' => 'API handtekening',
    'gateways:api_password' => 'API wachtwoord',
    'gateways:api_username' => 'API gebruikersnaam',
    /** End Payment Gateways * */
    /** Kitchen Area * */
    'kitchen:edit_comment' => 'Wijzig reactie',
    'kitchen:kitchen_name' => 'Klantgedeelte',
    'kitchen:pleaselogin' => 'Geef aub uw wachtwoord om toegang te krijgen tot uw account',
    'kitchen:nocomments' => 'Er zijn nog geen reacties.',
    'kitchen:comment' => 'Reactie',
    'kitchen:comments' => 'Reacties',
    'kitchen:file' => 'Bestand',
    'kitchen:submitcomment' => 'Nieuwe reactie',
    'kitchen:attachment' => 'Bijlage',
    'kitchen:saidon' => 'geplaatst op :1, om :2',
    'kitchen:subjectinvoice' => 'Nieuwe reactie op factuur #',
    'kitchen:subjectestimate' => 'Nieuwe reactie op offerte #',
    'kitchen:subjectproject' => 'Nieuwe reactie op project:',
    'kitchen:subjecttask' => 'Nieuwe reactie op taak:',
    'kitchen:subjectproposal' => 'Nieuwe reactie op voorstel:',
    'kitchen:backtodashboard' => 'Terug naar Dashboard',
    'kitchen:client_welcome' => 'Klantgedeelte voor:',
    'kitchen:urltosend' => 'Klant toegang url',
    'kitchen:nopassphrase' => 'Momenteel is het "wachtwoord" van de klant niet ingesteld. Dit betekend dat ze gewoon toegang hebben via de URL en dus geen wachtwoord nodig hebben om hun klantgedeelte te benaderen. Als u dit gedeelte toch wilt beveiligen met een simpel wachtwoord kunt u de klant bewerken en daar een wachtwoord instellen.',
    'kitchen:passphraseset' => 'Deze klant heeft een wachtwoord ingesteld',
    'kitchen:passphrase' => 'Wachtwoord',
    'kitchen:description' => 'Dit is de url om naar uw klant te zenden om ze toegang te geven tot het klantgedeelte waar ze projecten, facturen, etc.. kunnen bekijken.',
        /** END Kitchen Area * */
);

/** End of file: pancake_lang.php **/